name: Build and Push

on:
  push:
    branches:
      - main  # or specify your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: WebAPI/WebAPI
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  # Specify the .NET version you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish_output
      
    - name: Check current directory
      run: |
        ls -lah
        ls -lah publish_output/
        pwd
      
    - name: Push to another repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.RELEASE }}
        branch: devops_release  # Specify the branch of the other repository
        directory: ./publish_output  # Specify the directory containing the artifacts
