name: Build and Push

on:
  push:
    branches:
      - main  # or specify your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  # Specify the .NET version you're using

    - name: Restore dependencies
      working-directory: WebAPI/WebAPI
      run: dotnet restore

    - name: Build
      working-directory: WebAPI/WebAPI
      run: dotnet build --configuration Release

    - name: Publish
      working-directory: WebAPI/WebAPI
      run: dotnet publish -c Release -o publish_output

    - name: Push to another repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: devops_release  # Specify the branch of the other repository
        directory: ./publish_output  # Specify the directory containing the artifacts
