name: Publish and Push Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Publish
        run: |
          # Your build and publish commands here
          dotnet build
          dotnet publish -o ./publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-artifacts
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: published-artifacts
          path: ./published-artifacts

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: rhermano-dev/devops_release
          path: ./destination-repo

      - name: Copy Artifacts
        run: |
          cp -r ./published-artifacts/* ./destination-repo/

      - name: Commit and Push Artifacts
        run: |
          cd ./destination-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Publish artifacts"
          git push
