name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: WebAPI/WebAPITestProject
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'  # Specify the .NET version you're using

      - name: Restore dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release

      - name: Execute unit tests
        run: dotnet test
